### ISSUE TITLE
No use of Jquery and the JavaScript file as a dependency

### ISSUE THREAD

**Issue by ankitgaurav** [itsSayantan/chunk#1]
I think, by looking at the source code of the css and js files, that the jquery and chunk.js file dependencies are useless and only decrease the utility of the library as a whole.

All the manipulations mentioned can also be achieved with plain css modifications alone.
Do take note if you aim to make the repo a useful and adoptable one.

**Comment by itsSayantan** [comment]
The js part is important if you see that i have used attributes inside the
html as well.

Also i have changed the concept of containers and i will change that later
on

**Comment by itsSayantan** [comment]
I have completely changed the concept of containers and i will upload that shortly

**Comment by ankitgaurav** [comment]
Waiting for the upload.
